language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kpl5672/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kpl5672/docker-react npm run test
